development:
  images_config_path: "/data/www.andinatravelclub.com/config/images.yml"
  mail_config_path: "/data/www.andinatravelclub.com/config/mail.yml"
  database_config_path: "/data/www.andinatravelclub.com/config/database.yml"
test:
  images_config_path: "/data/www.andinatravelclub.com/config/images.yml"
  mail_config_path: "/data/www.andinatravelclub.com/config/mail.yml"
  database_config_path: "/data/www.andinatravelclub.com/config/database.yml"  
production:
  images_config_path: "/data/www.andinatravelclub.com/config/images.yml"
  mail_config_path: "/data/www.andinatravelclub.com/config/mail.yml"
  database_config_path: "/data/www.andinatravelclub.com/config/database.yml"  
