development:
  images_config_path: "/data/andina.vetmedic.com.pe/config/images.yml"
  mail_config_path: "/data/andina.vetmedic.com.pe/config/mail.yml"
  database_config_path: "/data/andina.vetmedic.com.pe/config/database.yml"
test:
  images_config_path: "/data/andina.vetmedic.com.pe/config/images.yml"
  mail_config_path: "/data/andina.vetmedic.com.pe/config/mail.yml"
  database_config_path: "/data/andina.vetmedic.com.pe/config/database.yml"  
production:
  images_config_path: "/data/andina.vetmedic.com.pe/config/images.yml"
  mail_config_path: "/data/andina.vetmedic.com.pe/config/mail.yml"
  database_config_path: "/data/andina.vetmedic.com.pe/config/database.yml"  
