<% 
  EXTERNAL_CONFIG_FILE_PATH = "#{::Rails.root.to_s}/config/config-routes.yml" if !defined?(EXTERNAL_CONFIG_FILE_PATH)
  config_file_exists = FileTest.exists?(EXTERNAL_CONFIG_FILE_PATH)

  case
  when config_file_exists
  # if it does exist, load it
  config_file = YAML.load_file(EXTERNAL_CONFIG_FILE_PATH)[::Rails.env]
  database_config_file = YAML.load_file(config_file['database_config_path'])[::Rails.env] if FileTest.exists?(config_file['database_config_path'])
  if database_config_file == nil
    database_config_file = {
                    :database_dev => "andina_dev",
                    :database_test => "andina_test",
                    :database_prod => "andina_prod",                    
                    :username => "andina",
                    :password => "andina"  
                  }
  end
  #
  when !config_file_exists && ( ::Rails.env=='development' || ::Rails.env=='test' )
  # otherwise use some sensible defaults, but only for dev or test
    database_config_file = {
                    :database_dev => "andina_dev",
                    :database_test => "andina_test",
                    :database_prod => "andina_prod",                    
                    :username => "andina",
                    :password => "andina"          
                  }
  else
    #if on prod, raise an error
    raise "#{EXTERNAL_CONFIG_FILE_PATH} configuration file is missing"
  end

%>
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: <%= database_config_file['database_dev'] %>
  pool: 5
  username: <%= database_config_file['username'] %>
  password: <%= database_config_file['password'] %>
  socket: /var/lib/mysql/mysql.sock

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: <%= database_config_file['database_test'] %>
  pool: 5
  username: <%= database_config_file['username'] %>
  password: <%= database_config_file['password'] %>
  socket: /var/lib/mysql/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: <%= database_config_file['database_prod'] %>
  pool: 5
  username: <%= database_config_file['username'] %>
  password: <%= database_config_file['password'] %>
  socket: /var/lib/mysql/mysql.sock
